// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar for the Physical AI & Humanoid Robotics textbook
  textbookSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: [
        'intro/intro-to-physical-ai',
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 1: ROS 2 Fundamentals',
      items: [
        'ros2/ros2-fundamentals',
        'ros2/quiz-ros2-fundamentals',
        // Additional ROS 2 chapters will be added as they are created
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 2: Simulation (Gazebo & Unity)',
      items: [
        'simulation/gazebo-physics',
        'simulation/quiz-simulation',
        // Additional simulation chapters will be added as they are created
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 3: NVIDIA Isaac',
      items: [
        'isaac/isaac-sim-basics',
        'isaac/quiz-isaac',
        // Additional Isaac chapters will be added as they are created
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action Systems',
      items: [
        'vla-ai/vla-implementation',
        'vla-ai/quiz-vla',
        // Additional VLA chapters will be added as they are created
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Capstone Project',
      items: [
        'capstone/final-capstone',
        'capstone/quiz-capstone',
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Appendices',
      items: [
        'deployment/hardware-setup',
        'deployment/gpu-requirements',
        'deployment/sim-to-real-notes',
      ],
      collapsed: true,
    }
  ],
};

export default sidebars;
